name : Simple CI/CD Pipeline
on:
  push:
    branches: ['main']
jobs:
  test-phase:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.13.12'
          
      - name: Run test in powershell
        shell: powershell
        run: |
          pip install pytest
          python -m pytest test_app.py

  deploy-phase:
      needs: test-phase
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: Deploy to local folder
          shell: powershell
          run: |
            $deployPath = "C:\DevOps"
            if (!(Test-Path $deployPath)) {
              New-Item -ItemType Directory -Path $deployPath
              echo "Folder created"
            }
            Copy-Item -Path "app.py" -Destination $deployPath
            echo "Application successfully deployed"

        - name: Save good files
          uses: actions/upload-artifact@v4
          with:
            name: final-app
            path: app.py
